### ISSUE TITLE
jest.useFakeTimers('modern'); don't work

### ISSUE THREAD

**Issue by chess777** [Trendyol/jest-testcontainers#37]
Hello!

I'm using your library to test with containers, but I have problem with using modern timers.

node.js: v14.17.6
jest: v27.2.1
@trendyol/jest-testcontainers: v2.1.0

Steps to reproduce:
1. Create new test environment
2. use jest.useFakeTimers('modern');
3. Receive error:
```
Cannot read property 'useFakeTimers' of undefined
TypeError: Cannot read property 'useFakeTimers' of undefined
    at Object.useFakeTimers (<projectRoot>\node_modules\jest-runtime\build\index.js:2165:38)
    at <projectRoot>\tests\js\helpers\setup.ts:528:10
    at Promise.then.completed (<projectRoot>\node_modules\jest-circus\build\utils.js:390:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (<projectRoot>\node_modules\jest-circus\build\utils.js:315:10)
    at _callCircusHook (<projectRoot>\node_modules\jest-circus\build\run.js:181:40)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at _runTestsForDescribeBlock (<projectRoot>\node_modules\jest-circus\build\run.js:47:7)
    at run (<projectRoot>\node_modules\jest-circus\build\run.js:25:3)
    at runAndTransformResultsToJestFormat (<projectRoot>\node_modules\jest-circus\build\legacy-code-todo-rewrite\jestAdapterInit.js:167:21)
```

I've checked and discovered that your library uses outdated `jest-environment-node`. May be you can move it to peerDependencies & import it dynamically?

**Comment by Zomono** [comment]
I am having the same problem. Is this project still maintained?

**Comment by Yengas** [comment]
Thanks for the pointers on how to fix this and detailed report. This should be fixed now. Please try version `2.1.1` and let us know if it works for you. Sorry for the late reply.
